### PR TITLE
fix: create `mysql` in DuckDB

### LINKED ISSUE #239: Unable to access 'mysql' database in myduckserver
## Description
When trying to access the 'mysql' database in myduckserver, the system shows error "database not found: mysql" despite the database being listed in `show databases` output.

## Reproduce steps
1. Start myduckserver container:
```bash
docker run -p 13306:3306 -p 15432:5432 apecloud/myduckserver:latest
```

2. Connect to server and verify databases:
```sql
mysql -h127.0.0.1 -P13306 -uroot

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| main               |
| mysql              |
| performance_schema |
| public             |
+--------------------+
5 rows in set (0.01 sec)
```

3. Try to access mysql database:
```sql
mysql> use mysql;
ERROR 1105 (HY000): unknown error: database not found: mysql
```

4. Direct connection attempt also fails:
```sql
mysql -h127.0.0.1 -P13306 -uroot -Dmysql
ERROR 1105 (HY000): unknown error: database not found: mysql
```

### PR DESCRIPTION
**Pull request by TianyuZhang1214**
Resolve #239

### CODE REVIEW

File: catalog/provider.go [hunk 1]
```diff
@@ -76,6 +76,19 @@ func NewDBProvider(dataDir, dbFile string) (*DatabaseProvider, error) {
 		}
 	}
 
+	for _, t := range internalSchemas {
+		if t.Catalog == name {
```
Comment (fanyang01) [inline catalog/provider.go:80]: This check is unneccesary. We will soon change the `mysql.db` file name.

**Review by fanyang01 — APPROVED** [review]
LGTM!
