### PR TITLE
fix: resolve compatibilities for Metabase (#340)

### LINKED ISSUE #342: Incorrect response packet for `Describe` command while handling extended protocol requests
Expected:
image
image

MyDuck produced:
image

It seems it's the `NoData` packet led to this problem.

### PR DESCRIPTION
**Pull request by VWagen1989**
This PR addresses the issues of the compatiblities between MyDuck and Metabase.
The other BI tools are not tested yet. If there still be compatibility issues for them, we should open another PR for them.

Ref #340 
Resolve #342

### CODE REVIEW

File: pgserver/iter.go [hunk 1]
```diff
@@ -197,6 +206,21 @@ func (iter *SqlRowIter) Next(ctx *sql.Context) (sql.Row, error) {
...
 
+	for _, idx := range iter.hugeInts {
+		switch v := iter.buffer[idx].(type) {
+		case nil:
+			continue
+		case *big.Int:
+			var n pgtype.Numeric
+			if err := n.Scan(v.String()); err != nil {
+				return nil, err
+			}
```
Comment (fanyang01) [inline pgserver/iter.go:217]: To be faster:
```
n := pgtype.Numeric{Int: v, Valid: true}
```

File: pgserver/stmt.go [hunk 2]
```diff
@@ -271,18 +271,121 @@ var (
...
+			`(?i)\b(FROM|JOIN|INTO)\s+(?:pg_catalog\.)?(?:"?(` + strings.Join(internalNames, "|") + `)"?)`)
 	})
 	return pgCatalogRegex
 }
 
 func ConvertToSys(sql string) string {
 	return getPgCatalogRegex().ReplaceAllString(RemoveComments(sql), "$1 __sys__.$2")
 }
+
+// The below code lines are generated by Claude Sonnet 3.5 and ChatGPT o1 preview
```
Comment (fanyang01) [inline pgserver/stmt.go:297]: Such comment is unnecessary

File: pgserver/stmt.go [hunk 3]
```diff
@@ -271,18 +271,121 @@ var (
...
+		// The pattern matches:
+		// - Branch A: "pg_catalog.<funcName>("
+		// - Branch B: "<funcName>(" without a preceding "."
+		pattern := `(?i)(?:pg_catalog\.("?(?:` + namesAlt + `)"?)\(|(^|[^\.])("?(?:` + namesAlt + `)"?)\()`
+		renameMacroRegex = regexp.MustCompile(pattern)
+	})
+	return renameMacroRegex
+}
+
+func ConvertPgCatalogFuncToSys(sql string) string {
```
Comment (fanyang01) [inline pgserver/stmt.go:328]: It would be better to add comments for these functions to explain what they are doing.

File: pgserver/iter.go (hunk 1 above)
Comment (VWagen1989) [reply pgserver/iter.go]: done

File: pgserver/connection_data.go [hunk 4]
```diff
@@ -58,11 +58,26 @@ type ConvertedStatement struct {
...
 	PgParsable         bool
 	HasSentRowDesc     bool
+	IsExtendedQuery    bool
 	SubscriptionConfig *SubscriptionConfig
 	BackupConfig       *BackupConfig
 	RestoreConfig      *RestoreConfig
 }
 
+func (cs ConvertedStatement) WithString(s string) ConvertedStatement {
+	return ConvertedStatement{
```
Comment (fanyang01) [inline pgserver/connection_data.go:68]: Maybe we should rename this field to `QueryString` (and this method to WithQueryString) to improve its clarity.

File: pgserver/in_place_handler.go [hunk 5]
```diff
@@ -121,130 +121,177 @@ func (h *ConnectionHandler) setPgSessionVar(name string, value any, useDefault b
...
-		return false, err
-	}
-	return true, h.run(ConvertedStatement{
-		String: fmt.Sprintf(`SELECT '%s' AS "pg_is_in_recovery";`, isInRecovery),
-		Tag:    "SELECT",
-	})
+type InPlaceHandler struct {
+	// ShouldHandledInPlace is a function that determines if the query should be
+	// handled in place and not passed to the engine.
+	ShouldHandledInPlace func(*ConnectionHandler, *ConvertedStatement) (bool, error)
```
Comment (fanyang01) [inline pgserver/in_place_handler.go:127]: `ShouldBeHandledInPlace`

File: pgserver/in_place_handler.go [hunk 6]
```diff
@@ -121,130 +121,177 @@ func (h *ConnectionHandler) setPgSessionVar(name string, value any, useDefault b
...
+type SelectionConversion struct {
+	needConvert func(*ConvertedStatement) bool
+	doConvert   func(*ConnectionHandler, *ConvertedStatement) error
+	// Indicate that the query will be converted to a constant snapshot query.
+	// The data will be fetched internally and used as a constant value for query.
+	// e.g. SELECT current_setting('application_name'); -> SELECT 'myDUCK' AS "current_setting";
+	// Be careful while handling extended queries, as the SQL statement requested by the client
+	// is a prepared statement. If we convert the query to a constant snapshot query, the client
+	// will not be able to fetch the fresh data from the server.
+	isConstSnapshot bool
```
Comment (fanyang01) [inline pgserver/in_place_handler.go:140]: What does `snapshot` mean here? Maybe `isConstant` or `Constant` is enough.

**Comment by fanyang01** [comment]
The failed `COPY DATABASE` test will be auto-fixed in DuckDB 1.2: https://github.com/duckdb/duckdb/pull/15548

**Review by fanyang01 — APPROVED** [review]
Thanks! Look good. It's the first BI tool that we can seamlessly integrate with. Congratulations!
