### PR TITLE
fix: add full_match_handler.go to convert the query.

### LINKED ISSUE #297: Support seemingly ambiguous reference
When trying to connect using `Npgsql` (in C#), it sends a sql like this:

```sql
SELECT pg_type.oid, enumlabel
FROM pg_enum
JOIN pg_type ON pg_type.oid=enumtypid
ORDER BY oid, enumsortorder;
```

The problem is that in real pg server, this can work properly. But in MyDuck Server, it brings us a bug (created by DuckDB):

```
Binder Error: Ambiguous reference to column name "oid" (use: "pg_type.oid" or "pg_enum.oid")
```

### PR DESCRIPTION
**Pull request by TianyuZhang1214**
This PR resolves issues #297 and #316, addressing compatibility challenges with [Npgsql](https://github.com/npgsql/npgsql) in C#.

#### Issue 1: Real Data for PostgreSQL System Tables
In [PostgresDatabaseInfo.cs](https://github.com/npgsql/npgsql/blob/main/src/Npgsql/PostgresDatabaseInfo.cs), 4 hard-coded queries are executed, with the results accessed via `ReadNonNullableString`. To ensure compatibility and non-null results, real PostgreSQL system table data are mirrored in MyDuck Server. Additionally, all PostgreSQL system table queries are redirected to their corresponding `__sys__.pg_xxx` tables in DuckDB.

#### Issue 2: Discontinuous Data in Batches
As discussed in #316, query results are split into multiple batches and returned discontinuously due to each batch containing a separate `RowDescription`. This PR introduces a mechanism to ensure that only a single `RowDescription` is returned per statement execution, providing a continuous result stream for better compatibility with Npgsql.

### CODE REVIEW

**Comment by fanyang01** [comment]
@NoyException Is this issue the final obstacle to making the C# client functional? If so, we should consider enabling the test in this PR.

**Comment by TianyuZhang1214** [comment]
> @NoyException Is this issue the final obstacle to making the C# client functional? If so, we should consider enabling the test in this PR.

I'll enable it.

File: catalog/initial_data.go [hunk 1]
```diff
@@ -0,0 +1,32 @@
+package catalog
+
+var InitialDatas = struct {
```
Comment (fanyang01) [inline catalog/initial_data.go:3]: "data" is a plural. `InitialDataTables`?

File: catalog/provider.go [hunk 2]
```diff
@@ -32,6 +32,7 @@ type DatabaseProvider struct {
 	dsn                       string
 	externalProcedureRegistry sql.ExternalStoredProcedureRegistry
 	ready                     bool
+	initialDataDir            string
```
Comment (fanyang01) [inline catalog/provider.go:35]: This design complicates the deployment. Instead of requiring the presence of these CSV files, we can use Go's `embed` feature: https://pkg.go.dev/embed

Comment (TianyuZhang1214) [reply catalog/provider.go:35]: Thanks! I'll fix it in next commit.

File: catalog/provider.go [hunk 3]
```diff
@@ -143,6 +144,39 @@ func (prov *DatabaseProvider) initCatalog() error {
...
+				defer os.Remove(tmpFile.Name())
+				defer tmpFile.Close()
+
+				// Write the initial data to the temporary file
+				if _, err := tmpFile.WriteString(initialFileContent); err != nil {
+					return fmt.Errorf("failed to write initial data to temporary file: %w", err)
+				}
+
+				// Execute the COPY command to insert data into the table
+				if _, err := prov.storage.ExecContext(
```
Comment (fanyang01) [inline catalog/provider.go:172]: `tmpFile.Sync()` should be called before reading from the DuckDB side.

File: initialdata/pg_class.csv [hunk 4]
```diff
@@ -0,0 +1,420 @@
+oid,relname,relnamespace,reltype,reloftype,relowner,relam,relfilenode,reltablespace,relpages,reltuples,relallvisible,reltoastrelid,relhasindex,relisshared,relpersistence,relkind,relnatts,relchecks,relhasrules,relhastriggers,relhassubclass,relrowsecurity,relforcerowsecurity,relispopulated,relreplident,relispartition,relrewrite,relfrozenxid,relminmxid,relacl,reloptions,relpartbound
```
Comment (fanyang01) [inline initialdata/pg_class.csv:1]: It would be better to add a script for generating these files:

```sh
CONTAINER_ID=$(docker run --rm -d -e POSTGRES_PASSWORD=postgres postgres)
docker exec -i $CONTAINER_ID psql -U postgres -c '\COPY pg_class TO STDOUT (FORMAT CSV)' > pg_class.csv
...
docker kill $CONTAINER_ID
```

File: pgserver/full_match_handler.go [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+// In contrast, PostgreSQL executes the query without error.
+// The issue arises because DuckDB cannot resolve the `oid` column unambiguously when referenced
+// without specifying the table. This behavior differs from PostgreSQL, which allows the ambiguous reference.
+//
+// Since handling all such cases is complex, we only handle a limited set of common queries,
+// especially those frequently used with PostgreSQL clients.
+
+var queryPatterns = map[*regexp.Regexp]string{
+	regexp.MustCompile(`(?is)^SELECT\s+pg_type\.oid,\s*enumlabel\s+FROM\s+pg_enum\s+JOIN\s+pg_type\s+ON\s+pg_type\.oid=enumtypid\s+ORDER\s+BY\s+oid,\s+enumsortorder$`): "SELECT pg_type.oid, pg_enum.enumlabel FROM pg_enum JOIN pg_type ON pg_type.oid=enumtypid ORDER BY pg_type.oid, pg_enum.enumsortorder;",
+}
```
Comment (fanyang01) [inline pgserver/full_match_handler.go:28]: Such long regular expressions are expensive to evaluate. Could we does something like:
```
if removeSpace(inputQuery) == pattern {
    ...
}
```
where `removeSpace` is a faster implementation? https://stackoverflow.com/a/32081891

File: initialdata/pg_class.csv (hunk 4 above)
Comment (TianyuZhang1214) [reply initialdata/pg_class.csv:1]: This approach may not work with cloud vendors in China, as the machine might not be able to connect to Docker Hub.

File: pgserver/full_match_handler.go (hunk 5 above)
Comment (TianyuZhang1214) [reply pgserver/full_match_handler.go:28]: Good idea. Will be fixed in next commit.

Comment (TianyuZhang1214) [reply pgserver/full_match_handler.go:45]: fixed

File: initialdata/pg_class.csv (hunk 4 above)
Comment (fanyang01) [reply initialdata/pg_class.csv:1]: I mean a script for maintainers to regenerate these files easily.

Comment (TianyuZhang1214) [reply initialdata/pg_class.csv:1]: Got it.I'll leave a script with README later.

Comment (TianyuZhang1214) [reply initialdata/pg_class.csv:1]: fixed

**Comment by TianyuZhang1214** [comment]
@fanyang01 
Maybe this PR is ready to merge?

**Review by fanyang01 — APPROVED** [review]
LGTM!
